version: '3.8'

services:
  postgres:
    ports:
      - "${DB_PORT:-5432}:5432"

  progress-tracker:
    ports:
      - "${APP_PORT:-9000}:8000"
    environment:
      DATABASE_URL: postgresql+psycopg://progress_user:progress_password@postgres:5432/progress_tracker