version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-progress_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-progress_password}
      POSTGRES_DB: ${POSTGRES_DB:-progress_tracker}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  postgres-dev:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_DEV_USER:-progress_user_dev}
      POSTGRES_PASSWORD: ${POSTGRES_DEV_PASSWORD:-progress_password_dev}
      POSTGRES_DB: ${POSTGRES_DEV_DB:-progress_tracker_dev}
    ports:
      - "5433:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    restart: unless-stopped

  progress-tracker:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://progress_user:progress_password@postgres:5432/progress_tracker
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - uploads_data:/app/web/static/uploads

volumes:
  postgres_data:
  postgres_dev_data:
  uploads_data: